#!/usr/bin/env bash

# Load rbenv automatically by appending
# the following to ~/.bash_profile:
eval "$(rbenv init -)"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
