#!/bin/sh
# Automatically adds branch name to the end of every commit message.

NAME=$(git branch | grep '*' | sed 's/* //')

if [ -z "$NAME" ]; then
   echo $(cat "$1")> "$1"
else
   echo "$NAME" " - " $
fi
